In [28]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_excel('Liver.xlsx')
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,NaN,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [7]:
df.isnull().sum().sum()

np.int64(40)

In [16]:
df.fillna(10,inplace=True)

In [17]:
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,10.0,16.0,18.0,10.0,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,10.0,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [19]:
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,NaN,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [22]:
df.fillna(method='ffill',inplace=True)

C:\Users\mhask\AppData\Local\Temp\ipykernel_15832\4116506308.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',inplace=True)

In [23]:
df.isnull().sum().sum()

np.int64(2)

In [24]:
df.fillna(method='bfill',inplace=True)

C:\Users\mhask\AppData\Local\Temp\ipykernel_15832\1626352436.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',inplace=True)

In [25]:
df.isnull().sum().sum()

np.int64(0)

In [26]:
df.to_excel('Test11am.xlsx')

In [27]:
df2=pd.read_excel('Liver.xlsx')
df2

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,NaN,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [30]:
df2["Age"] = df["Age"].fillna(df["Age"].mean())

In [31]:
df2

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,62.0,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [32]:
df2["Alkphos"] = df["Alkphos"].fillna(df["Alkphos"].max())

In [33]:
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,699.0,16.0,18.0,7.5,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,62.0,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [34]:
df3=pd.read_excel('Liver.xlsx')
df3

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
3,NaN,Male,1.0,0.4,182.0,14.0,20.0,6.8,3.4,1.00,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [35]:
df3.dropna()

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1
7,29.0,Female,0.9,0.3,202.0,14.0,11.0,6.7,3.6,1.10,1
9,55.0,Male,0.7,0.2,290.0,53.0,58.0,6.8,3.4,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0

In [36]:
df4=pd.read_excel('Liver.xlsx')
df4

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [37]:
df4.dropna(how='all')

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
5,46.0,Male,1.8,0.7,NaN,19.0,14.0,7.6,4.4,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [40]:
df4.dropna(how='all',inplace=True)

In [41]:
df4

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
5,46.0,Male,1.8,0.7,NaN,19.0,14.0,7.6,4.4,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [42]:
df4.to_excel('pratiksha1.xlsx')