### Recursion Practice

In [5]:
def countdown(n):
    if n==0:
         return 0
    print(n)
    return countdown(n-1)

countdown(5)

5
4
3
2
1

0

In [6]:
def countup(number):
    if number < 1:
        return []
    count_list = countup(number - 1)
    count_list.append(number)
    return count_list

print(countup(5))

[1, 2, 3, 4, 5]

In [7]:
def range_of_numbers(start_num, end_num):
    
    if start_num == end_num:
        return [start_num]
    if start_num > end_num:
        return 'invlaid numbers try again' 

    list_numbers = range_of_numbers(start_num ,end_num - 1)
    list_numbers.append(end_num)
    return list_numbers

print(range_of_numbers(1,9))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
def change_string(string):
    if string == "":
        return ""
    return change_string(string[1:]) + string[0]

print(change_string("Anand"))

dnanA

### Python libraries

In [3]:
import numpy as np
import matplotlib as mp
import seaborn as sn
import pandas as pd

In [5]:
print('hello python libraries')

hello python libraries

In [11]:
a = 29
b = 49

print('addition of the numbers is: ',a+b)
print('substraction of the numbers is: ',a-b)
print('multiplication of the numbers is: ',a*b)
print('division of the numbers is: ',a/b)

addition of the numbers is:  78
substraction of the numbers is:  -20
multiplication of the numbers is:  1421
division of the numbers is:  0.5918367346938775

In [22]:
n=int(input('Enter number: '))
def count_of(n):
    for i in range (1,n):
        yield i
a = count_of(n)
print(next(a))
print(next(a))

Enter number:  5

1
2

### Numpy libraries

In [2]:
import numpy as np

In [5]:
a=np.array([24,32,32,2,24,42])
b=np.array([3,44,2,1,5,31])

print(a + b)
print(a + 2)
print(b + 5)

[27 76 34  3 29 73]
[26 34 34  4 26 44]
[ 8 49  7  6 10 36]

In [7]:
arr = np.array([25,36,10])

print(arr[0]*arr[0])
print(np.sqrt(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

625
[5.         6.         3.16227766]
23.666666666666668
71
36
10

In [19]:
arr = np.arange(1,15)


print("array is: ",arr)
print("shape of the array is: ",arr.shape)
print("size of the array is: ",arr.size)


print("reshape the array into 2 row 7 col: ",arr.reshape(2,7))

array is:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shape of the array is:  (14,)
size of the array is:  14
reshape the array into 2 row 7 col:  [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

In [21]:
arr = np.array([[10,30,20,40],[50,60,70,80]])

arr.shape
arr.reshape(-1)

array([10, 30, 20, 40, 50, 60, 70, 80])

In [24]:
a=np.array([12,45,33])
b=np.array([34,5,33])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[12 45 33]
 [34  5 33]]
[12 45 33 34  5 33]

In [28]:
print(np.random.rand(3))
print(np.random.randint(1,10,5))
print(np.random.rand(3,3))

[0.52964999 0.00266342 0.69504444]
[8 5 8 6 1]
[[0.70589424 0.94812443 0.49995971]
 [0.06325212 0.21352174 0.99834058]
 [0.92901194 0.98823344 0.12351498]]

In [30]:
arr = np.array([2,3,55,33])

view = arr.view()
copy = arr.copy()

print(arr)
print(view)
print(copy)

[ 2  3 55 33]
[ 2  3 55 33]
[ 2  3 55 33]

In [32]:
arr[0]=199

print(arr)
print(view)
print(copy)

[199   3  55  33]
[199   3  55  33]
[ 2  3 55 33]

In [ ]:
arr = np.array([1,2,4,5,3])

### Pandas libraries

In [6]:
import pandas as pd

In [16]:
df=pd.read_excel(r'C:\Users\Swami-Anand\Downloads\MessyData _Text Function.xlsx')
df

,last 4 employee id,Employee prefix,Mid Employee_Id,Replace_emp,Employee_ID,clean_lower_name,clean_upper_name,clean_proper_name,Count_clean_name,Create Full_Name_Department,...,Messy_Location,Department,clean_salary_label,Salary_As_numeric,Salary_As_Text,Phone,Clean_Location_Chain,Location_Chain,Clean_Record,final_emp_label
0,1001,EMP,1001,EMP-1001,EMP-1001,priya sharma,PRIYA SHARMA,Priya Sharma,12,Priya Sharma Operations,...,Aurangabad-Maharashtra,Operations,Salary: 45000,45000,45000,+91-7599310825,Pune-Mumbai-Mumbai,Pune-Pune-Mumbai,"EMP-1001, Priya Sharma, priya.sharma@company...","EMP-1001, Priya Sharma, Operations"
1,1002,EMP,1002,EMP-1002,EMP-1002,priya kulkarni,PRIYA KULKARNI,Priya Kulkarni,14,Priya Kulkarni Operations,...,"Nagpur, Maharashtra",Operations,Salary: 35000,35000,35000,+91-7939042955,Mumbai-Pune-Mumbai,Mumbai-Pune-Pune,"EMP-1002, Priya Kulkarni, priya.kulkarni@gma...","EMP-1002, Priya Kulkarni, Operations"
2,1003,CON,1003,EMP-1003,CON-1003,amit sharma,AMIT SHARMA,Amit Sharma,11,Amit Sharma HR,...,Ahmednagar-Maharashtra,HR,Salary: 80000,80000,"80,000",+91-9340505846,Nagpur-Pune-Mumbai,Nagpur-Pune-Pune,"EMP-1003, Amit Sharma, amit.sharma@yahoo.com...","EMP-1003, Amit Sharma, HR"
3,1004,EMP,1004,EMP-1004,EMP-1004,vikas kulkarni,VIKAS KULKARNI,Vikas Kulkarni,14,Vikas Kulkarni HR,...,"nashik , Maharashtra",HR,Salary: 60000,60000,60000,+91-8461364854,Pune-Nashik-Mumbai,Pune-Nashik-Pune,"EMP-1004, Vikas Kulkarni, vikas.kulkarni@gma...","EMP-1004, Vikas Kulkarni, HR"
4,1005,STF,1005,EMP-1005,STF-1005,sneha patil,SNEHA PATIL,Sneha Patil,11,Sneha Patil Operations,...,PUNE-Maharashtra,Operations,Salary: 35000,35000,35000,+91-8541804686,Pune-Nashik-Mumbai,Pune-Nashik-Pune,"EMP-1005, Sneha Patil, sneha.patil@gmail.com...","EMP-1005, Sneha Patil, Operations"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,EMP,1096,EMP-1096,EMP-1096,amit joshi,AMIT JOSHI,Amit Joshi,10,Amit Joshi Operations,...,"mumbai , Maharashtra",Operations,Salary: 30000,30000,"30,000",+91-8754569613,Nagpur-Pune-Mumbai,Nagpur-Pune-Pune,"EMP-1096, Amit Joshi, amit.joshi@gmail.com, ...","EMP-1096, Amit Joshi, Operations"
96,1097,STF,1097,EMP-1097,STF-1097,vikas deshmukh,VIKAS DESHMUKH,Vikas Deshmukh,14,Vikas Deshmukh HR,...,Pune-Maharashtra,HR,Salary: 50000,50000,50000,+91-8950049698,Pune-Mumbai-Mumbai,Pune-Pune-Mumbai,"EMP-1097, Vikas Deshmukh, vikas.deshmukh@yah...","EMP-1097, Vikas Deshmukh, HR"
97,1098,STF,1098,EMP-1098,STF-1098,rohan kulkarni,ROHAN KULKARNI,Rohan Kulkarni,14,Rohan Kulkarni HR,...,"Aurangabad, Maharashtra",HR,Salary: 35000,35000,35000,+91-9338877621,Mumbai-Pune-Mumbai,Mumbai-Pune-Pune,"EMP-1098, Rohan Kulkarni, rohan.kulkarni @ya...","EMP-1098, Rohan Kulkarni, HR"
98,1099,EMP,1099,EMP-1099,EMP-1099,rohan kumar,ROHAN KUMAR,Rohan Kumar,11,Rohan Kumar IT,...,Pune-Maharashtra,IT,Salary: 50000,50000,"50,000",+91-9555694670,Pune-Nashik-Mumbai,Pune-Nashik-Pune,"EMP-1099, Rohan Kumar, rohan.kumar@gmail.com...","EMP-1099, Rohan Kumar, IT"
99,1100,CON,1100,EMP-1100,CON-1100,priya singh,PRIYA SINGH,Priya Singh,11,Priya Singh IT,...,"AURANGABAD, Maharashtra",IT,Salary: 60000,60000,60000,+91-8169288485,Nagpur-Pune-Mumbai,Nagpur-Pune-Pune,"EMP-1100, Priya Singh, priya.singh@company.c...","EMP-1100, Priya Singh, IT"

In [17]:
df.head
df.isnull
df.shape
df.sum

<bound method DataFrame.sum of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001
1                 1002             EMP             1002    EMP-1002
2                 1003             CON             1003    EMP-1003
3                 1004             EMP             1004    EMP-1004
4                 1005             STF             1005    EMP-1005
..                 ...             ...              ...         ...
95                1096             EMP             1096    EMP-1096
96                1097             STF             1097    EMP-1097
97                1098             STF             1098    EMP-1098
98                1099             EMP             1099    EMP-1099
99                1100             CON             1100    EMP-1100

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHARMA      Priya Sharma
1     EMP-1002   priya kulkarni   PRIYA KULKARNI    Priya Kulkarni
2     CON-1003      amit sharma      AMIT SHARMA       Amit Sharma
3     EMP-1004   vikas kulkarni   VIKAS KULKARNI    Vikas Kulkarni
4     STF-1005      sneha patil      SNEHA PATIL       Sneha Patil
..         ...              ...              ...               ...
95    EMP-1096       amit joshi       AMIT JOSHI        Amit Joshi
96    STF-1097   vikas deshmukh   VIKAS DESHMUKH    Vikas Deshmukh
97    STF-1098   rohan kulkarni   ROHAN KULKARNI    Rohan Kulkarni
98    EMP-1099      rohan kumar      ROHAN KUMAR       Rohan Kumar
99    CON-1100      priya singh      PRIYA SINGH       Priya Singh

    Count_clean_name Create Full_Name_Department  ...  \
0                 12     Priya Sharma Operations  ...
1                 14   Priya Kulkarni Operations  ...
2                 11              Amit Sharma HR  ...
3                 14           Vikas Kulkarni HR  ...
4                 11      Sneha Patil Operations  ...
..               ...                         ...  ...
95                10       Amit Joshi Operations  ...
96                14           Vikas Deshmukh HR  ...
97                14           Rohan Kulkarni HR  ...
98                11              Rohan Kumar IT  ...
99                11              Priya Singh IT  ...

             Messy_Location  Department  clean_salary_label Salary_As_numeric  \
0    Aurangabad-Maharashtra  Operations       Salary: 45000             45000
1       Nagpur, Maharashtra  Operations       Salary: 35000             35000
2    Ahmednagar-Maharashtra          HR       Salary: 80000             80000
3      nashik , Maharashtra          HR       Salary: 60000             60000
4          PUNE-Maharashtra  Operations       Salary: 35000             35000
..                      ...         ...                 ...               ...
95     mumbai , Maharashtra  Operations       Salary: 30000             30000
96         Pune-Maharashtra          HR       Salary: 50000             50000
97  Aurangabad, Maharashtra          HR       Salary: 35000             35000
98         Pune-Maharashtra          IT       Salary: 50000             50000
99  AURANGABAD, Maharashtra          IT       Salary: 60000             60000

   Salary_As_Text           Phone Clean_Location_Chain    Location_Chain  \
0           45000  +91-7599310825   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
1           35000  +91-7939042955   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
2         80,000   +91-9340505846   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
3           60000  +91-8461364854   Pune-Nashik-Mumbai  Pune-Nashik-Pune
4           35000  +91-8541804686   Pune-Nashik-Mumbai  Pune-Nashik-Pune
..            ...             ...                  ...               ...
95        30,000   +91-8754569613   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
96          50000  +91-8950049698   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
97          35000  +91-9338877621   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
98        50,000   +91-9555694670   Pune-Nashik-Mumbai  Pune-Nashik-Pune
99          60000  +91-8169288485   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune

                                         Clean_Record  \
0   EMP-1001,  Priya Sharma,  priya.sharma@company...
1   EMP-1002,  Priya Kulkarni,  priya.kulkarni@gma...
2   EMP-1003,  Amit Sharma,  amit.sharma@yahoo.com...
3   EMP-1004,  Vikas Kulkarni,  vikas.kulkarni@gma...
4   EMP-1005,  Sneha Patil,  sneha.patil@gmail.com...
..                                                ...
95  EMP-1096,  Amit Joshi,  amit.joshi@gmail.com, ...
96  EMP-1097,  Vikas Deshmukh,  vikas.deshmukh@yah...
97  EMP-1098,  Rohan Kulkarni,  rohan.kulkarni @ya...
98  EMP-1099,  Rohan Kumar,  rohan.kumar@gmail.com...
99  EMP-1100,  Priya Singh,  priya.singh@company.c...

                         final_emp_label
0     EMP-1001, Priya Sharma, Operations
1   EMP-1002, Priya Kulkarni, Operations
2              EMP-1003, Amit Sharma, HR
3           EMP-1004, Vikas Kulkarni, HR
4      EMP-1005, Sneha Patil, Operations
..                                   ...
95      EMP-1096, Amit Joshi, Operations
96          EMP-1097, Vikas Deshmukh, HR
97          EMP-1098, Rohan Kulkarni, HR
98             EMP-1099, Rohan Kumar, IT
99             EMP-1100, Priya Singh, IT

[100 rows x 44 columns]>

In [18]:
df.isna

<bound method DataFrame.isna of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001
1                 1002             EMP             1002    EMP-1002
2                 1003             CON             1003    EMP-1003
3                 1004             EMP             1004    EMP-1004
4                 1005             STF             1005    EMP-1005
..                 ...             ...              ...         ...
95                1096             EMP             1096    EMP-1096
96                1097             STF             1097    EMP-1097
97                1098             STF             1098    EMP-1098
98                1099             EMP             1099    EMP-1099
99                1100             CON             1100    EMP-1100

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHARMA      Priya Sharma
1     EMP-1002   priya kulkarni   PRIYA KULKARNI    Priya Kulkarni
2     CON-1003      amit sharma      AMIT SHARMA       Amit Sharma
3     EMP-1004   vikas kulkarni   VIKAS KULKARNI    Vikas Kulkarni
4     STF-1005      sneha patil      SNEHA PATIL       Sneha Patil
..         ...              ...              ...               ...
95    EMP-1096       amit joshi       AMIT JOSHI        Amit Joshi
96    STF-1097   vikas deshmukh   VIKAS DESHMUKH    Vikas Deshmukh
97    STF-1098   rohan kulkarni   ROHAN KULKARNI    Rohan Kulkarni
98    EMP-1099      rohan kumar      ROHAN KUMAR       Rohan Kumar
99    CON-1100      priya singh      PRIYA SINGH       Priya Singh

    Count_clean_name Create Full_Name_Department  ...  \
0                 12     Priya Sharma Operations  ...
1                 14   Priya Kulkarni Operations  ...
2                 11              Amit Sharma HR  ...
3                 14           Vikas Kulkarni HR  ...
4                 11      Sneha Patil Operations  ...
..               ...                         ...  ...
95                10       Amit Joshi Operations  ...
96                14           Vikas Deshmukh HR  ...
97                14           Rohan Kulkarni HR  ...
98                11              Rohan Kumar IT  ...
99                11              Priya Singh IT  ...

             Messy_Location  Department  clean_salary_label Salary_As_numeric  \
0    Aurangabad-Maharashtra  Operations       Salary: 45000             45000
1       Nagpur, Maharashtra  Operations       Salary: 35000             35000
2    Ahmednagar-Maharashtra          HR       Salary: 80000             80000
3      nashik , Maharashtra          HR       Salary: 60000             60000
4          PUNE-Maharashtra  Operations       Salary: 35000             35000
..                      ...         ...                 ...               ...
95     mumbai , Maharashtra  Operations       Salary: 30000             30000
96         Pune-Maharashtra          HR       Salary: 50000             50000
97  Aurangabad, Maharashtra          HR       Salary: 35000             35000
98         Pune-Maharashtra          IT       Salary: 50000             50000
99  AURANGABAD, Maharashtra          IT       Salary: 60000             60000

   Salary_As_Text           Phone Clean_Location_Chain    Location_Chain  \
0           45000  +91-7599310825   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
1           35000  +91-7939042955   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
2         80,000   +91-9340505846   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
3           60000  +91-8461364854   Pune-Nashik-Mumbai  Pune-Nashik-Pune
4           35000  +91-8541804686   Pune-Nashik-Mumbai  Pune-Nashik-Pune
..            ...             ...                  ...               ...
95        30,000   +91-8754569613   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
96          50000  +91-8950049698   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
97          35000  +91-9338877621   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
98        50,000   +91-9555694670   Pune-Nashik-Mumbai  Pune-Nashik-Pune
99          60000  +91-8169288485   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune

                                         Clean_Record  \
0   EMP-1001,  Priya Sharma,  priya.sharma@company...
1   EMP-1002,  Priya Kulkarni,  priya.kulkarni@gma...
2   EMP-1003,  Amit Sharma,  amit.sharma@yahoo.com...
3   EMP-1004,  Vikas Kulkarni,  vikas.kulkarni@gma...
4   EMP-1005,  Sneha Patil,  sneha.patil@gmail.com...
..                                                ...
95  EMP-1096,  Amit Joshi,  amit.joshi@gmail.com, ...
96  EMP-1097,  Vikas Deshmukh,  vikas.deshmukh@yah...
97  EMP-1098,  Rohan Kulkarni,  rohan.kulkarni @ya...
98  EMP-1099,  Rohan Kumar,  rohan.kumar@gmail.com...
99  EMP-1100,  Priya Singh,  priya.singh@company.c...

                         final_emp_label
0     EMP-1001, Priya Sharma, Operations
1   EMP-1002, Priya Kulkarni, Operations
2              EMP-1003, Amit Sharma, HR
3           EMP-1004, Vikas Kulkarni, HR
4      EMP-1005, Sneha Patil, Operations
..                                   ...
95      EMP-1096, Amit Joshi, Operations
96          EMP-1097, Vikas Deshmukh, HR
97          EMP-1098, Rohan Kulkarni, HR
98             EMP-1099, Rohan Kumar, IT
99             EMP-1100, Priya Singh, IT

[100 rows x 44 columns]>

In [19]:
df.shape

(100, 44)

In [20]:
df.isna

<bound method DataFrame.isna of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001
1                 1002             EMP             1002    EMP-1002
2                 1003             CON             1003    EMP-1003
3                 1004             EMP             1004    EMP-1004
4                 1005             STF             1005    EMP-1005
..                 ...             ...              ...         ...
95                1096             EMP             1096    EMP-1096
96                1097             STF             1097    EMP-1097
97                1098             STF             1098    EMP-1098
98                1099             EMP             1099    EMP-1099
99                1100             CON             1100    EMP-1100

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHARMA      Priya Sharma
1     EMP-1002   priya kulkarni   PRIYA KULKARNI    Priya Kulkarni
2     CON-1003      amit sharma      AMIT SHARMA       Amit Sharma
3     EMP-1004   vikas kulkarni   VIKAS KULKARNI    Vikas Kulkarni
4     STF-1005      sneha patil      SNEHA PATIL       Sneha Patil
..         ...              ...              ...               ...
95    EMP-1096       amit joshi       AMIT JOSHI        Amit Joshi
96    STF-1097   vikas deshmukh   VIKAS DESHMUKH    Vikas Deshmukh
97    STF-1098   rohan kulkarni   ROHAN KULKARNI    Rohan Kulkarni
98    EMP-1099      rohan kumar      ROHAN KUMAR       Rohan Kumar
99    CON-1100      priya singh      PRIYA SINGH       Priya Singh

    Count_clean_name Create Full_Name_Department  ...  \
0                 12     Priya Sharma Operations  ...
1                 14   Priya Kulkarni Operations  ...
2                 11              Amit Sharma HR  ...
3                 14           Vikas Kulkarni HR  ...
4                 11      Sneha Patil Operations  ...
..               ...                         ...  ...
95                10       Amit Joshi Operations  ...
96                14           Vikas Deshmukh HR  ...
97                14           Rohan Kulkarni HR  ...
98                11              Rohan Kumar IT  ...
99                11              Priya Singh IT  ...

             Messy_Location  Department  clean_salary_label Salary_As_numeric  \
0    Aurangabad-Maharashtra  Operations       Salary: 45000             45000
1       Nagpur, Maharashtra  Operations       Salary: 35000             35000
2    Ahmednagar-Maharashtra          HR       Salary: 80000             80000
3      nashik , Maharashtra          HR       Salary: 60000             60000
4          PUNE-Maharashtra  Operations       Salary: 35000             35000
..                      ...         ...                 ...               ...
95     mumbai , Maharashtra  Operations       Salary: 30000             30000
96         Pune-Maharashtra          HR       Salary: 50000             50000
97  Aurangabad, Maharashtra          HR       Salary: 35000             35000
98         Pune-Maharashtra          IT       Salary: 50000             50000
99  AURANGABAD, Maharashtra          IT       Salary: 60000             60000

   Salary_As_Text           Phone Clean_Location_Chain    Location_Chain  \
0           45000  +91-7599310825   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
1           35000  +91-7939042955   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
2         80,000   +91-9340505846   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
3           60000  +91-8461364854   Pune-Nashik-Mumbai  Pune-Nashik-Pune
4           35000  +91-8541804686   Pune-Nashik-Mumbai  Pune-Nashik-Pune
..            ...             ...                  ...               ...
95        30,000   +91-8754569613   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
96          50000  +91-8950049698   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
97          35000  +91-9338877621   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
98        50,000   +91-9555694670   Pune-Nashik-Mumbai  Pune-Nashik-Pune
99          60000  +91-8169288485   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune

                                         Clean_Record  \
0   EMP-1001,  Priya Sharma,  priya.sharma@company...
1   EMP-1002,  Priya Kulkarni,  priya.kulkarni@gma...
2   EMP-1003,  Amit Sharma,  amit.sharma@yahoo.com...
3   EMP-1004,  Vikas Kulkarni,  vikas.kulkarni@gma...
4   EMP-1005,  Sneha Patil,  sneha.patil@gmail.com...
..                                                ...
95  EMP-1096,  Amit Joshi,  amit.joshi@gmail.com, ...
96  EMP-1097,  Vikas Deshmukh,  vikas.deshmukh@yah...
97  EMP-1098,  Rohan Kulkarni,  rohan.kulkarni @ya...
98  EMP-1099,  Rohan Kumar,  rohan.kumar@gmail.com...
99  EMP-1100,  Priya Singh,  priya.singh@company.c...

                         final_emp_label
0     EMP-1001, Priya Sharma, Operations
1   EMP-1002, Priya Kulkarni, Operations
2              EMP-1003, Amit Sharma, HR
3           EMP-1004, Vikas Kulkarni, HR
4      EMP-1005, Sneha Patil, Operations
..                                   ...
95      EMP-1096, Amit Joshi, Operations
96          EMP-1097, Vikas Deshmukh, HR
97          EMP-1098, Rohan Kulkarni, HR
98             EMP-1099, Rohan Kumar, IT
99             EMP-1100, Priya Singh, IT

[100 rows x 44 columns]>

In [21]:
df.sum

<bound method DataFrame.sum of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001
1                 1002             EMP             1002    EMP-1002
2                 1003             CON             1003    EMP-1003
3                 1004             EMP             1004    EMP-1004
4                 1005             STF             1005    EMP-1005
..                 ...             ...              ...         ...
95                1096             EMP             1096    EMP-1096
96                1097             STF             1097    EMP-1097
97                1098             STF             1098    EMP-1098
98                1099             EMP             1099    EMP-1099
99                1100             CON             1100    EMP-1100

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHARMA      Priya Sharma
1     EMP-1002   priya kulkarni   PRIYA KULKARNI    Priya Kulkarni
2     CON-1003      amit sharma      AMIT SHARMA       Amit Sharma
3     EMP-1004   vikas kulkarni   VIKAS KULKARNI    Vikas Kulkarni
4     STF-1005      sneha patil      SNEHA PATIL       Sneha Patil
..         ...              ...              ...               ...
95    EMP-1096       amit joshi       AMIT JOSHI        Amit Joshi
96    STF-1097   vikas deshmukh   VIKAS DESHMUKH    Vikas Deshmukh
97    STF-1098   rohan kulkarni   ROHAN KULKARNI    Rohan Kulkarni
98    EMP-1099      rohan kumar      ROHAN KUMAR       Rohan Kumar
99    CON-1100      priya singh      PRIYA SINGH       Priya Singh

    Count_clean_name Create Full_Name_Department  ...  \
0                 12     Priya Sharma Operations  ...
1                 14   Priya Kulkarni Operations  ...
2                 11              Amit Sharma HR  ...
3                 14           Vikas Kulkarni HR  ...
4                 11      Sneha Patil Operations  ...
..               ...                         ...  ...
95                10       Amit Joshi Operations  ...
96                14           Vikas Deshmukh HR  ...
97                14           Rohan Kulkarni HR  ...
98                11              Rohan Kumar IT  ...
99                11              Priya Singh IT  ...

             Messy_Location  Department  clean_salary_label Salary_As_numeric  \
0    Aurangabad-Maharashtra  Operations       Salary: 45000             45000
1       Nagpur, Maharashtra  Operations       Salary: 35000             35000
2    Ahmednagar-Maharashtra          HR       Salary: 80000             80000
3      nashik , Maharashtra          HR       Salary: 60000             60000
4          PUNE-Maharashtra  Operations       Salary: 35000             35000
..                      ...         ...                 ...               ...
95     mumbai , Maharashtra  Operations       Salary: 30000             30000
96         Pune-Maharashtra          HR       Salary: 50000             50000
97  Aurangabad, Maharashtra          HR       Salary: 35000             35000
98         Pune-Maharashtra          IT       Salary: 50000             50000
99  AURANGABAD, Maharashtra          IT       Salary: 60000             60000

   Salary_As_Text           Phone Clean_Location_Chain    Location_Chain  \
0           45000  +91-7599310825   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
1           35000  +91-7939042955   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
2         80,000   +91-9340505846   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
3           60000  +91-8461364854   Pune-Nashik-Mumbai  Pune-Nashik-Pune
4           35000  +91-8541804686   Pune-Nashik-Mumbai  Pune-Nashik-Pune
..            ...             ...                  ...               ...
95        30,000   +91-8754569613   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
96          50000  +91-8950049698   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
97          35000  +91-9338877621   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
98        50,000   +91-9555694670   Pune-Nashik-Mumbai  Pune-Nashik-Pune
99          60000  +91-8169288485   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune

                                         Clean_Record  \
0   EMP-1001,  Priya Sharma,  priya.sharma@company...
1   EMP-1002,  Priya Kulkarni,  priya.kulkarni@gma...
2   EMP-1003,  Amit Sharma,  amit.sharma@yahoo.com...
3   EMP-1004,  Vikas Kulkarni,  vikas.kulkarni@gma...
4   EMP-1005,  Sneha Patil,  sneha.patil@gmail.com...
..                                                ...
95  EMP-1096,  Amit Joshi,  amit.joshi@gmail.com, ...
96  EMP-1097,  Vikas Deshmukh,  vikas.deshmukh@yah...
97  EMP-1098,  Rohan Kulkarni,  rohan.kulkarni @ya...
98  EMP-1099,  Rohan Kumar,  rohan.kumar@gmail.com...
99  EMP-1100,  Priya Singh,  priya.singh@company.c...

                         final_emp_label
0     EMP-1001, Priya Sharma, Operations
1   EMP-1002, Priya Kulkarni, Operations
2              EMP-1003, Amit Sharma, HR
3           EMP-1004, Vikas Kulkarni, HR
4      EMP-1005, Sneha Patil, Operations
..                                   ...
95      EMP-1096, Amit Joshi, Operations
96          EMP-1097, Vikas Deshmukh, HR
97          EMP-1098, Rohan Kulkarni, HR
98             EMP-1099, Rohan Kumar, IT
99             EMP-1100, Priya Singh, IT

[100 rows x 44 columns]>

In [22]:
df.isna

<bound method DataFrame.isna of     last 4 employee id Employee prefix  Mid Employee_Id Replace_emp  \
0                 1001             EMP             1001    EMP-1001
1                 1002             EMP             1002    EMP-1002
2                 1003             CON             1003    EMP-1003
3                 1004             EMP             1004    EMP-1004
4                 1005             STF             1005    EMP-1005
..                 ...             ...              ...         ...
95                1096             EMP             1096    EMP-1096
96                1097             STF             1097    EMP-1097
97                1098             STF             1098    EMP-1098
98                1099             EMP             1099    EMP-1099
99                1100             CON             1100    EMP-1100

   Employee_ID clean_lower_name clean_upper_name clean_proper_name  \
0     EMP-1001     priya sharma     PRIYA SHARMA      Priya Sharma
1     EMP-1002   priya kulkarni   PRIYA KULKARNI    Priya Kulkarni
2     CON-1003      amit sharma      AMIT SHARMA       Amit Sharma
3     EMP-1004   vikas kulkarni   VIKAS KULKARNI    Vikas Kulkarni
4     STF-1005      sneha patil      SNEHA PATIL       Sneha Patil
..         ...              ...              ...               ...
95    EMP-1096       amit joshi       AMIT JOSHI        Amit Joshi
96    STF-1097   vikas deshmukh   VIKAS DESHMUKH    Vikas Deshmukh
97    STF-1098   rohan kulkarni   ROHAN KULKARNI    Rohan Kulkarni
98    EMP-1099      rohan kumar      ROHAN KUMAR       Rohan Kumar
99    CON-1100      priya singh      PRIYA SINGH       Priya Singh

    Count_clean_name Create Full_Name_Department  ...  \
0                 12     Priya Sharma Operations  ...
1                 14   Priya Kulkarni Operations  ...
2                 11              Amit Sharma HR  ...
3                 14           Vikas Kulkarni HR  ...
4                 11      Sneha Patil Operations  ...
..               ...                         ...  ...
95                10       Amit Joshi Operations  ...
96                14           Vikas Deshmukh HR  ...
97                14           Rohan Kulkarni HR  ...
98                11              Rohan Kumar IT  ...
99                11              Priya Singh IT  ...

             Messy_Location  Department  clean_salary_label Salary_As_numeric  \
0    Aurangabad-Maharashtra  Operations       Salary: 45000             45000
1       Nagpur, Maharashtra  Operations       Salary: 35000             35000
2    Ahmednagar-Maharashtra          HR       Salary: 80000             80000
3      nashik , Maharashtra          HR       Salary: 60000             60000
4          PUNE-Maharashtra  Operations       Salary: 35000             35000
..                      ...         ...                 ...               ...
95     mumbai , Maharashtra  Operations       Salary: 30000             30000
96         Pune-Maharashtra          HR       Salary: 50000             50000
97  Aurangabad, Maharashtra          HR       Salary: 35000             35000
98         Pune-Maharashtra          IT       Salary: 50000             50000
99  AURANGABAD, Maharashtra          IT       Salary: 60000             60000

   Salary_As_Text           Phone Clean_Location_Chain    Location_Chain  \
0           45000  +91-7599310825   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
1           35000  +91-7939042955   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
2         80,000   +91-9340505846   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
3           60000  +91-8461364854   Pune-Nashik-Mumbai  Pune-Nashik-Pune
4           35000  +91-8541804686   Pune-Nashik-Mumbai  Pune-Nashik-Pune
..            ...             ...                  ...               ...
95        30,000   +91-8754569613   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune
96          50000  +91-8950049698   Pune-Mumbai-Mumbai  Pune-Pune-Mumbai
97          35000  +91-9338877621   Mumbai-Pune-Mumbai  Mumbai-Pune-Pune
98        50,000   +91-9555694670   Pune-Nashik-Mumbai  Pune-Nashik-Pune
99          60000  +91-8169288485   Nagpur-Pune-Mumbai  Nagpur-Pune-Pune

                                         Clean_Record  \
0   EMP-1001,  Priya Sharma,  priya.sharma@company...
1   EMP-1002,  Priya Kulkarni,  priya.kulkarni@gma...
2   EMP-1003,  Amit Sharma,  amit.sharma@yahoo.com...
3   EMP-1004,  Vikas Kulkarni,  vikas.kulkarni@gma...
4   EMP-1005,  Sneha Patil,  sneha.patil@gmail.com...
..                                                ...
95  EMP-1096,  Amit Joshi,  amit.joshi@gmail.com, ...
96  EMP-1097,  Vikas Deshmukh,  vikas.deshmukh@yah...
97  EMP-1098,  Rohan Kulkarni,  rohan.kulkarni @ya...
98  EMP-1099,  Rohan Kumar,  rohan.kumar@gmail.com...
99  EMP-1100,  Priya Singh,  priya.singh@company.c...

                         final_emp_label
0     EMP-1001, Priya Sharma, Operations
1   EMP-1002, Priya Kulkarni, Operations
2              EMP-1003, Amit Sharma, HR
3           EMP-1004, Vikas Kulkarni, HR
4      EMP-1005, Sneha Patil, Operations
..                                   ...
95      EMP-1096, Amit Joshi, Operations
96          EMP-1097, Vikas Deshmukh, HR
97          EMP-1098, Rohan Kulkarni, HR
98             EMP-1099, Rohan Kumar, IT
99             EMP-1100, Priya Singh, IT

[100 rows x 44 columns]>

### Numpy

In [3]:
import numpy as np

In [5]:
l=[12,3,42,34,55,34]
type(l)

list

In [7]:
a=np.array(1)
print(a)
print(type(a))
print(a.shape)

1
<class 'numpy.ndarray'>
()

In [8]:
arr2d = np.array([[1,2,3,55],[4,5,6,67]])
print(arr2d)
print(arr2d.shape)

[[ 1  2  3 55]
 [ 4  5  6 67]]
(2, 4)

In [12]:
arr=np.arange(5,1)
arr

array([], dtype=int64)

In [13]:
l=np.linspace(1,10,20)
l

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [14]:
arr = np.array([[1,2,3,5],[4,5,6,9]])
print(arr.shape)   # (2,4)

(2, 4)

In [15]:
print(arr.ndim)    # 2 dimensions

2

In [16]:
print(arr.size)    # 8 elements

8

In [19]:
print(arr.dtype)

int64

In [20]:
arr.nbytes

64

In [27]:
arr=np.array([1,2,3,54,5,6,9])
arr.min()

np.int64(1)

In [28]:
arr.max()

np.int64(54)

In [29]:
arr = np.array([10,20,30,40,50])

print(arr[0])    
print(arr[-1])   
print(arr[0:4])

10
50
[10 20 30 40]

In [30]:
print(arr[2::-1])

[30 20 10]

In [31]:
a = np.array([1,2,3,7])
b = np.array([4,5,6,5])

print(a + b)   
print(a - b)   
print(a * b)   
print(a / b)   
print(a ** 2)

[ 5  7  9 12]
[-3 -3 -3  2]
[ 4 10 18 35]
[0.25 0.4  0.5  1.4 ]
[ 1  4  9 49]

In [32]:
b = np.array([1,2,3,7])
c = np.array([5,5,5,5])
print(b+c)

[ 6  7  8 12]

In [33]:
print(b+2)

[3 4 5 9]

In [34]:
print(b*10)

[10 20 30 70]

In [35]:
arr = np.array([25,36,10])

print(np.sqrt(arr))   # Square root
print(np.mean(arr))   # Average
print(np.sum(arr))    # Sum
print(np.max(arr))    # Max
print(np.min(arr))

[5.         6.         3.16227766]
23.666666666666668
71
36
10

In [36]:
arr*arr

array([ 625, 1296,  100])

In [37]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [39]:
print(arr.reshape(-1))
print(arr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)

In [40]:
ar=np.array([[10,20,30],[40,50,60]])
ar

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
ar.shape

(2, 3)

In [42]:
ar.reshape(-1)

array([10, 20, 30, 40, 50, 60])

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))  # Vertical stack
print(np.hstack((a,b)))  # Horizontal stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

In [44]:
print(np.random.rand(3))       # 3 random numbers [0-1]
print(np.random.randint(10000,99999,1)) # 5 random int (1-9)
print(np.random.randn(3,3))

[0.07527641 0.37844563 0.36756673]
[74890]
[[ 0.90201683  0.55699583  0.41544618]
 [-1.13681149 -0.44807435 -0.37068762]
 [ 0.0108681   0.48992847  0.54803722]]

In [45]:
arr = np.array([1,2,88,4])
view = arr.view()
copy = arr.copy()
print(arr)
print(view)
print(copy)

[ 1  2 88  4]
[ 1  2 88  4]
[ 1  2 88  4]

In [46]:
arr[0]=100

In [47]:
print(arr)
print(view)
print(copy)

[100   2  88   4]
[100   2  88   4]
[ 1  2 88  4]

In [48]:
arr = np.array([1,2,3,4,5])

np.save("myarray.npy", arr)       # Save
loaded = np.load("myarray.npy")   # Load

print(loaded)

[1 2 3 4 5]

### Pandas

In [49]:
import pandas as pd

In [50]:
data = [10, 20, 30, 40]

s = pd.Series(data)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [51]:
data1 = [10, 20, 30, 40]

s = pd.Series(data1,index=['raj','om','jay','raghu'])

print(s)
s.to_excel('Test1.xlsx',index=False)

raj      10
om       20
jay      30
raghu    40
dtype: int64

In [52]:
df = pd.DataFrame({
    "Date": pd.date_range("2024-01-01", periods=10),
    "City": ["Pune","Mumbai","Pune","Delhi","Mumbai","Pune","Delhi","Mumbai","Pune","Delhi"],
    "Product": ["A","B","A","B","A","B","A","B","A","B"],
    "Sales": [100,200,150,300,250,180,220,270,160,310],
    "Profit": [20,40,30,60,50,35,45,55,32,65]
})
df

        Date    City Product  Sales  Profit
0 2024-01-01    Pune       A    100      20
1 2024-01-02  Mumbai       B    200      40
2 2024-01-03    Pune       A    150      30
3 2024-01-04   Delhi       B    300      60
4 2024-01-05  Mumbai       A    250      50
5 2024-01-06    Pune       B    180      35
6 2024-01-07   Delhi       A    220      45
7 2024-01-08  Mumbai       B    270      55
8 2024-01-09    Pune       A    160      32
9 2024-01-10   Delhi       B    310      65

In [53]:
df.to_excel('batch11amnew1.xlsx',index=False)

In [54]:
df2=pd.read_excel('batch11amnew1.xlsx')
df2

        Date    City Product  Sales  Profit
0 2024-01-01    Pune       A    100      20
1 2024-01-02  Mumbai       B    200      40
2 2024-01-03    Pune       A    150      30
3 2024-01-04   Delhi       B    300      60
4 2024-01-05  Mumbai       A    250      50
5 2024-01-06    Pune       B    180      35
6 2024-01-07   Delhi       A    220      45
7 2024-01-08  Mumbai       B    270      55
8 2024-01-09    Pune       A    160      32
9 2024-01-10   Delhi       B    310      65

In [57]:
df.isnull().sum().sum()

np.int64(0)

In [58]:
df.isnull().sum()

Date       0
City       0
Product    0
Sales      0
Profit     0
dtype: int64

In [62]:
df['City'].fillna(method='ffill')

C:\Users\Swami-Anand\AppData\Local\Temp\ipykernel_24464\2639993032.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['City'].fillna(method='ffill')

0      Pune
1    Mumbai
2      Pune
3     Delhi
4    Mumbai
5      Pune
6     Delhi
7    Mumbai
8      Pune
9     Delhi
Name: City, dtype: object

In [63]:
df

        Date    City Product  Sales  Profit
0 2024-01-01    Pune       A    100      20
1 2024-01-02  Mumbai       B    200      40
2 2024-01-03    Pune       A    150      30
3 2024-01-04   Delhi       B    300      60
4 2024-01-05  Mumbai       A    250      50
5 2024-01-06    Pune       B    180      35
6 2024-01-07   Delhi       A    220      45
7 2024-01-08  Mumbai       B    270      55
8 2024-01-09    Pune       A    160      32
9 2024-01-10   Delhi       B    310      65

In [65]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     10 non-null     datetime64[ns]
 1   City     10 non-null     object
 2   Product  10 non-null     object
 3   Sales    10 non-null     int64
 4   Profit   10 non-null     int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 532.0+ bytes
None

In [ ]:
df.head()

        Date    City Product  Sales  Profit
0 2024-01-01    Pune       A    100      20
1 2024-01-02  Mumbai       B    200      40
2 2024-01-03    Pune       A    150      30
3 2024-01-04   Delhi       B    300      60
4 2024-01-05  Mumbai       A    250      50

In [68]:
df.tail()

        Date    City Product  Sales  Profit
5 2024-01-06    Pune       B    180      35
6 2024-01-07   Delhi       A    220      45
7 2024-01-08  Mumbai       B    270      55
8 2024-01-09    Pune       A    160      32
9 2024-01-10   Delhi       B    310      65

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel('Liver.xlsx')
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [4]:
df.isnull().sum().sum()

np.int64(50)

In [5]:
df.fillna(10,inplace=True)

In [6]:
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,10.0,16.0,18.0,10.0,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,10.0,10,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.00,10.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [7]:
df

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,10.0,16.0,18.0,10.0,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,10.0,10,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.00,10.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [10]:
df.fillna(method='ffill')

C:\Users\Swami-Anand\AppData\Local\Temp\ipykernel_26444\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,10.0,16.0,18.0,10.0,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,10.0,10,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.00,10.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [11]:
df.isnull().sum().sum()

np.int64(0)

In [13]:
df.fillna(method='bfill')

C:\Users\Swami-Anand\AppData\Local\Temp\ipykernel_26444\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,10.0,16.0,18.0,10.0,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,10.0,10,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.00,10.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [14]:
df.isnull().sum().sum()

np.int64(0)

In [15]:
df.to_excel('liver_clean.xlsx')

In [16]:
df2=pd.read_excel('liver_clean.xlsx')
df2

,Unnamed: 0,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,0,65,Female,0.7,0.1,10,16,18,10.0,3.3,0.90,1
1,1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,3,10,10,10.0,10.0,10,10,10,10.0,10.0,10.00,10
4,4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...,...
578,578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,0
579,579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,0

In [17]:
df2["Age"] = df["Age"].fillna(df["Age"].mean())

In [18]:
df2

,Unnamed: 0,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,0,65.0,Female,0.7,0.1,10,16,18,10.0,3.3,0.90,1
1,1,62.0,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,2,62.0,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,3,10.0,10,10.0,10.0,10,10,10,10.0,10.0,10.00,10
4,4,72.0,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...,...
578,578,60.0,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,0
579,579,40.0,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,580,52.0,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,581,31.0,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,582,38.0,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,0

In [19]:
df2["Alkphos"] = df["Alkphos"].fillna(df["Alkphos"].max())

In [20]:
df2

,Unnamed: 0,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,0,65.0,Female,0.7,0.1,10.0,16,18,10.0,3.3,0.90,1
1,1,62.0,Male,10.9,5.5,699.0,64,100,7.5,3.2,0.74,1
2,2,62.0,Male,7.3,4.1,490.0,60,68,7.0,3.3,0.89,1
3,3,10.0,10,10.0,10.0,10.0,10,10,10.0,10.0,10.00,10
4,4,72.0,Male,3.9,2.0,195.0,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...,...
578,578,60.0,Male,0.5,0.1,500.0,20,34,5.9,1.6,0.37,0
579,579,40.0,Male,0.6,0.1,98.0,35,31,6.0,3.2,1.10,1
580,580,52.0,Male,0.8,0.2,245.0,48,49,6.4,3.2,1.00,1
581,581,31.0,Male,1.3,0.5,184.0,29,32,6.8,3.4,1.00,1
582,582,38.0,Male,1.0,0.3,216.0,21,24,7.3,4.4,1.50,0

In [21]:
df3=pd.read_excel('Liver.xlsx')
df3

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [22]:
df3.dropna()

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
7,29.0,Female,0.9,0.3,202.0,14.0,11.0,6.7,3.6,1.10,1.0
9,55.0,Male,0.7,0.2,290.0,53.0,58.0,6.8,3.4,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [23]:
df4=pd.read_excel('Liver.xlsx')
df4

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [24]:
df4.dropna(how='all')

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
5,46.0,Male,1.8,0.7,NaN,19.0,14.0,7.6,4.4,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [25]:
df4.dropna(how='all',inplace=True)

In [26]:
df4

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
0,65.0,Female,0.7,0.1,NaN,16.0,18.0,NaN,3.3,0.90,1.0
1,62.0,Male,10.9,5.5,699.0,64.0,100.0,7.5,3.2,0.74,1.0
2,62.0,Male,7.3,4.1,490.0,60.0,68.0,7.0,3.3,0.89,1.0
4,72.0,Male,3.9,2.0,195.0,27.0,59.0,7.3,2.4,0.40,1.0
5,46.0,Male,1.8,0.7,NaN,19.0,14.0,7.6,4.4,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
578,60.0,Male,0.5,0.1,500.0,20.0,34.0,5.9,1.6,0.37,0.0
579,40.0,Male,0.6,0.1,98.0,35.0,31.0,6.0,3.2,1.10,1.0
580,52.0,Male,0.8,0.2,245.0,48.0,49.0,6.4,3.2,1.00,1.0
581,31.0,Male,1.3,0.5,184.0,29.0,32.0,6.8,3.4,1.00,1.0
582,38.0,Male,1.0,0.3,216.0,21.0,24.0,7.3,4.4,1.50,0.0

In [27]:
df4.to_excel('Liver1.xlsx')