In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("student_placement_practice.csv")
df

,student_id,branch,gender,city,cgpa,attendance_pct,projects_completed,internship_months,certifications_count,coding_score,aptitude_score,communication_score,backlogs,study_hours_per_week,placement_status,salary_lpa
0,STU0001,ENTC,Male,Nagpur,8.07,90.7,3,2.0,1,59.7,74.0,67.3,1,18.9,Not Placed,NaN
1,STU0002,AI/ML,Male,Aurangabad,7.54,78.4,4,6.0,3,54.0,42.7,62.6,1,1.4,Not Placed,NaN
2,STU0003,Mechanical,Male,Aurangabad,7.61,84.9,1,1.0,2,65.6,74.7,84.1,0,14.8,Not Placed,NaN
3,STU0004,ENTC,Male,Other,8.29,83.5,1,0.0,2,61.4,51.0,66.1,0,19.6,Not Placed,NaN
4,STU0005,CSE,Female,Aurangabad,6.84,54.5,0,3.0,1,61.7,76.5,81.2,0,19.3,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,STU0975,AI/ML,Female,Nagpur,9.45,100.0,4,0.0,1,72.0,85.0,81.8,0,8.9,Placed,6.94
1208,STU0412,ENTC,Male,Other,6.11,95.7,4,1.0,0,56.8,56.2,54.2,1,17.2,Not Placed,NaN
1209,STU0856,IT,Male,Aurangabad,6.98,78.6,5,8.0,2,67.1,77.1,73.4,0,14.6,Not Placed,NaN
1210,STU0821,CSE,Male,Pune,7.76,73.1,1,2.0,2,36.8,63.1,72.1,0,13.8,Placed,4.13
1211,STU0045,Mechanical,Female,Nagpur,8.35,83.8,3,0.0,1,63.1,68.9,92.4,1,17.8,Placed,5.40

In [13]:
df.head()

,student_id,branch,gender,city,cgpa,attendance_pct,projects_completed,internship_months,certifications_count,coding_score,aptitude_score,communication_score,backlogs,study_hours_per_week,placement_status,salary_lpa
0,STU0001,ENTC,Male,Nagpur,8.07,90.7,3,2.0,1,59.7,74.0,67.3,1,18.9,Not Placed,NaN
1,STU0002,AI/ML,Male,Aurangabad,7.54,78.4,4,6.0,3,54.0,42.7,62.6,1,1.4,Not Placed,NaN
2,STU0003,Mechanical,Male,Aurangabad,7.61,84.9,1,1.0,2,65.6,74.7,84.1,0,14.8,Not Placed,NaN
3,STU0004,ENTC,Male,Other,8.29,83.5,1,0.0,2,61.4,51.0,66.1,0,19.6,Not Placed,NaN
4,STU0005,CSE,Female,Aurangabad,6.84,54.5,0,3.0,1,61.7,76.5,81.2,0,19.3,Not Placed,NaN

In [16]:
df.shape

(1212, 16)

In [17]:
df.columns

Index(['student_id', 'branch', 'gender', 'city', 'cgpa', 'attendance_pct',
       'projects_completed', 'internship_months', 'certifications_count',
       'coding_score', 'aptitude_score', 'communication_score', 'backlogs',
       'study_hours_per_week', 'placement_status', 'salary_lpa'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            1212 non-null   object
 1   branch                1212 non-null   object
 2   gender                1212 non-null   object
 3   city                  1182 non-null   object
 4   cgpa                  1212 non-null   float64
 5   attendance_pct        1170 non-null   float64
 6   projects_completed    1212 non-null   int64
 7   internship_months     1194 non-null   float64
 8   certifications_count  1212 non-null   int64
 9   coding_score          1182 non-null   float64
 10  aptitude_score        1212 non-null   float64
 11  communication_score   1188 non-null   float64
 12  backlogs              1212 non-null   int64
 13  study_hours_per_week  1212 non-null   float64
 14  placement_status      1212 non-null   object
 15  salary_lpa            477 non-null    float64
dtypes: float64(8), int64(3), object(5)
memory usage: 151.6+ KB

In [9]:
df.describe()

,cgpa,attendance_pct,projects_completed,internship_months,certifications_count,coding_score,aptitude_score,communication_score,backlogs,study_hours_per_week,salary_lpa
count,1212.000000,1170.000000,1212.000000,1194.000000,1212.000000,1182.000000,1212.000000,1188.000000,1212.000000,1212.000000,477.000000
mean,7.583317,82.107350,3.002475,3.412898,2.237624,63.684433,67.663366,68.561953,0.740924,13.952063,6.018532
std,1.030434,9.729398,1.761829,3.348874,1.466827,11.732564,12.901364,13.909282,0.870970,5.864795,1.224158
min,4.300000,45.000000,0.000000,0.000000,0.000000,30.500000,20.200000,20.000000,0.000000,0.000000,2.410000
25%,6.870000,75.500000,2.000000,0.000000,1.000000,55.625000,59.100000,58.475000,0.000000,10.000000,5.230000
50%,7.570000,82.300000,3.000000,3.000000,2.000000,63.200000,67.700000,69.050000,1.000000,13.900000,6.000000
75%,8.230000,88.800000,4.000000,6.000000,3.000000,71.700000,76.300000,78.225000,1.000000,17.900000,6.870000
max,10.000000,100.000000,10.000000,12.000000,9.000000,100.000000,100.000000,100.000000,5.000000,32.100000,9.380000

In [18]:
df.isnull().sum()

student_id                0
branch                    0
gender                    0
city                     30
cgpa                      0
attendance_pct           42
projects_completed        0
internship_months        18
certifications_count      0
coding_score             30
aptitude_score            0
communication_score      24
backlogs                  0
study_hours_per_week      0
placement_status          0
salary_lpa              735
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(12)

In [23]:
print("Dataset shape:", df.shape)
df.info()

Dataset shape: (1212, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            1212 non-null   object
 1   branch                1212 non-null   object
 2   gender                1212 non-null   object
 3   city                  1182 non-null   object
 4   cgpa                  1212 non-null   float64
 5   attendance_pct        1170 non-null   float64
 6   projects_completed    1212 non-null   int64
 7   internship_months     1194 non-null   float64
 8   certifications_count  1212 non-null   int64
 9   coding_score          1182 non-null   float64
 10  aptitude_score        1212 non-null   float64
 11  communication_score   1188 non-null   float64
 12  backlogs              1212 non-null   int64
 13  study_hours_per_week  1212 non-null   float64
 14  placement_status      1212 non-null   object
 15  salary_lpa            477 non-null    float64
dtypes: float64(8), int64(3), object(5)
memory usage: 151.6+ KB

In [24]:
print("Number of rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

Number of rows and columns: (1212, 16)

Column names:
['student_id', 'branch', 'gender', 'city', 'cgpa', 'attendance_pct', 'projects_completed', 'internship_months', 'certifications_count', 'coding_score', 'aptitude_score', 'communication_score', 'backlogs', 'study_hours_per_week', 'placement_status', 'salary_lpa']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            1212 non-null   object
 1   branch                1212 non-null   object
 2   gender                1212 non-null   object
 3   city                  1182 non-null   object
 4   cgpa                  1212 non-null   float64
 5   attendance_pct        1170 non-null   float64
 6   projects_completed    1212 non-null   int64
 7   internship_months     1194 non-null   float64
 8   certifications_count  1212 non-null   int64
 9   coding_score          1182 non-null   float64
 10  aptitude_score        1212 non-null   float64
 11  communication_score   1188 non-null   float64
 12  backlogs              1212 non-null   int64
 13  study_hours_per_week  1212 non-null   float64
 14  placement_status      1212 non-null   object
 15  salary_lpa            477 non-null    float64
dtypes: float64(8), int64(3), object(5)
memory usage: 151.6+ KB

In [28]:
df.describe(include="all")

,student_id,branch,gender,city,cgpa,attendance_pct,projects_completed,internship_months,certifications_count,coding_score,aptitude_score,communication_score,backlogs,study_hours_per_week,placement_status,salary_lpa
count,1212,1212,1212,1182,1212.000000,1170.000000,1212.000000,1194.000000,1212.000000,1182.000000,1212.000000,1188.000000,1212.000000,1212.000000,1212,477.000000
unique,1200,6,3,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
top,STU1121,CSE,Male,Pune,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not Placed,NaN
freq,2,314,696,325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,735,NaN
mean,NaN,NaN,NaN,NaN,7.583317,82.107350,3.002475,3.412898,2.237624,63.684433,67.663366,68.561953,0.740924,13.952063,NaN,6.018532
std,NaN,NaN,NaN,NaN,1.030434,9.729398,1.761829,3.348874,1.466827,11.732564,12.901364,13.909282,0.870970,5.864795,NaN,1.224158
min,NaN,NaN,NaN,NaN,4.300000,45.000000,0.000000,0.000000,0.000000,30.500000,20.200000,20.000000,0.000000,0.000000,NaN,2.410000
25%,NaN,NaN,NaN,NaN,6.870000,75.500000,2.000000,0.000000,1.000000,55.625000,59.100000,58.475000,0.000000,10.000000,NaN,5.230000
50%,NaN,NaN,NaN,NaN,7.570000,82.300000,3.000000,3.000000,2.000000,63.200000,67.700000,69.050000,1.000000,13.900000,NaN,6.000000
75%,NaN,NaN,NaN,NaN,8.230000,88.800000,4.000000,6.000000,3.000000,71.700000,76.300000,78.225000,1.000000,17.900000,NaN,6.870000
max,NaN,NaN,NaN,NaN,10.000000,100.000000,10.000000,12.000000,9.000000,100.000000,100.000000,100.000000,5.000000,32.100000,NaN,9.380000

In [29]:
df.isnull().sum()

student_id                0
branch                    0
gender                    0
city                     30
cgpa                      0
attendance_pct           42
projects_completed        0
internship_months        18
certifications_count      0
coding_score             30
aptitude_score            0
communication_score      24
backlogs                  0
study_hours_per_week      0
placement_status          0
salary_lpa              735
dtype: int64

In [30]:
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent[missing_percent > 0].sort_values(ascending=False)

salary_lpa             60.643564
attendance_pct          3.465347
city                    2.475248
coding_score            2.475248
communication_score     1.980198
internship_months       1.485149
dtype: float64

In [31]:
df.duplicated().sum()

np.int64(12)

In [32]:
df[df.duplicated()]

,student_id,branch,gender,city,cgpa,attendance_pct,projects_completed,internship_months,certifications_count,coding_score,aptitude_score,communication_score,backlogs,study_hours_per_week,placement_status,salary_lpa
1200,STU1179,CSE,Female,Aurangabad,7.47,82.3,3,6.0,1,63.5,64.4,70.8,2,9.8,Not Placed,NaN
1201,STU0866,Civil,Male,Pune,7.93,86.9,1,0.0,2,65.4,71.5,71.5,1,13.7,Not Placed,NaN
1202,STU0102,ENTC,Male,Nashik,6.86,80.5,4,0.0,0,68.7,75.0,77.5,0,11.9,Not Placed,NaN
1203,STU0440,ENTC,Male,Pune,5.50,73.2,4,4.0,3,50.4,53.0,70.1,1,11.0,Not Placed,NaN
1204,STU0059,CSE,Male,Pune,6.96,79.6,2,6.0,1,60.5,62.7,52.9,0,12.4,Not Placed,NaN
1205,STU1121,ENTC,Female,Nagpur,4.30,91.3,4,3.0,2,64.3,61.9,53.8,1,11.8,Not Placed,NaN
1206,STU0324,IT,Male,Mumbai,7.42,70.8,5,8.0,5,62.9,57.0,43.1,0,14.3,Placed,7.04
1207,STU0975,AI/ML,Female,Nagpur,9.45,100.0,4,0.0,1,72.0,85.0,81.8,0,8.9,Placed,6.94
1208,STU0412,ENTC,Male,Other,6.11,95.7,4,1.0,0,56.8,56.2,54.2,1,17.2,Not Placed,NaN
1209,STU0856,IT,Male,Aurangabad,6.98,78.6,5,8.0,2,67.1,77.1,73.4,0,14.6,Not Placed,NaN
1210,STU0821,CSE,Male,Pune,7.76,73.1,1,2.0,2,36.8,63.1,72.1,0,13.8,Placed,4.13
1211,STU0045,Mechanical,Female,Nagpur,8.35,83.8,3,0.0,1,63.1,68.9,92.4,1,17.8,Placed,5.40

In [33]:
df.isnull().sum()

student_id                0
branch                    0
gender                    0
city                     30
cgpa                      0
attendance_pct           42
projects_completed        0
internship_months        18
certifications_count      0
coding_score             30
aptitude_score            0
communication_score      24
backlogs                  0
study_hours_per_week      0
placement_status          0
salary_lpa              735
dtype: int64

In [34]:
df.isnull().sum().div(len(df)).mul(100).round(2)

student_id               0.00
branch                   0.00
gender                   0.00
city                     2.48
cgpa                     0.00
attendance_pct           3.47
projects_completed       0.00
internship_months        1.49
certifications_count     0.00
coding_score             2.48
aptitude_score           0.00
communication_score      1.98
backlogs                 0.00
study_hours_per_week     0.00
placement_status         0.00
salary_lpa              60.64
dtype: float64

In [35]:
df.duplicated().sum()

np.int64(12)

In [36]:
df.duplicated(subset=["gender"]).sum()

np.int64(1209)